Use YAML::load_file to workaround missing to_ruby method
Reproducable on Ubuntu 11.10 when running `rake spec`:

  1) rays deploy no parameters should deploy all modules from the project root
     Failure/Error: module_instances << generate(module_type, name).first
     NoMethodError:
       undefined method `to_ruby' for #<Syck::Map:0x00000002ed2428>
     # ./lib/rays/models/project.rb:8:in `initialize'